name: Deploy Nest Backend to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker for Google Cloud
        run: gcloud auth configure-docker

      - name: Build and Push Docker Image
        run: |
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/nest-backend:${{ github.sha }}
          docker build -t $IMAGE .
          docker push $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy nest-backend \
            --image $IMAGE \
            --platform managed \
            --region europe-central2 \
            --allow-unauthenticated \
            --env-vars-file cloudrun.env.yaml
