name: Deploy Backend to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker for Google Cloud
        run: gcloud auth configure-docker

      - name: Build Docker image
        working-directory: ./server
        run: |
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/nest-backend:${{ github.sha }}
          docker build -t $IMAGE .
          docker push $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        working-directory: ./server
        run: |
          gcloud run deploy nest-backend \
            --image $IMAGE \
            --platform managed \
            --region europe-central2 \
            --allow-unauthenticated \
            --env-vars-file cloudrun.env.yaml
